services:
  - type: web
    name: andrew-portfolio
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: RENDER
        value: true
      - key: NODE_ENV
        value: production
    disk:
      name: portfolio-storage
      mountPath: /opt/render/project/src
      sizeGB: 2
